export  let states=[
    {
        id:1,
          username:'manish',
            email:'shakyamanish976@gmail.com',
            phone:'9860106659',
            dob:'1998-10-29',
            city:'Kathmandu',
            district:'Kathmandu',
            provience:'3',
            country:'Nepal',
    },
    {
        id:2,
          username:'arjan',
            email:'arjan@gmail.com',
            phone:'9860120202',
            dob:'1998-10-29',
            city:'Kathmandu',
            district:'Kathmandu',
            provience:'3',
            country:'Nepal',
    }
]